### ISSUE TITLE
typo: redundant yaml

### ISSUE THREAD

**Issue by WindowsXp-Beta** [nebuly-ai/nos#29]
Hi, I was building the `gpu-partitioner` and ran into an issue saying `lstat /the/path/to/nos/config/gpupartitioner/default/gpu_partitioner_metrics_service.yaml.yaml: no such file or directory`.
Then I located the cause:
https://github.com/nebuly-ai/nos/blob/d93537ea0384e3ee6b633fd4f2658cb972074d61/config/gpupartitioner/default/kustomization.yaml#L19
Is it a typo?

**Comment by Telemaco019** [comment]
Hi @WindowsXp-Beta, you are right, that's a typo. Thanks for spotting it! 

In case you have already fixed it and want to open a PR it would be super appreciated! Otherwise, I'll fix it soon. Thanks!
