### ISSUE TITLE
doc: wrong make targets

### ISSUE THREAD

**Issue by WindowsXp-Beta** [nebuly-ai/nos#32]
While building the nos I found the doc was a bit outdated.
The make targets in [this](https://docs.nebuly.com/nos/developer/getting-started/#build-components) part should all begin with `docker-`.

**Comment by Telemaco019** [comment]
Thanks for spotting it! Yes, I agree that page is a bit outdated. It also does not include the Makefile targets for the GPU Agent, and there are a few formatting errors.  Let me know if you'd like to have this issue assigned to you, otherwise I'll fix it in the next few days!

**Comment by WindowsXp-Beta** [comment]
I'd love to. Maybe I can fix 31 and 32 in one PR since they're all small tweaks?

**Comment by Telemaco019** [comment]
Sure! Thanks for the contribution!
